baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Denver Sprinkler Start Up and Repair'

# collections:
#   services:
#     output: true
#     permalink: /services/:path/
#   team:
#     output: true
#     permalink: /team/:path/
#   testimonials:
#     output: true
#     permalink: /testimonials/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: UA-115742833-3

url: 'http://www.denversprinklerblowout.com/'
plugins:
  - jekyll-environment-variables
  - jekyll-seo-tag
  - jekyll-sitemap
